version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    # ports:
    #   - "27017:27017"
    # volumes:
    #   - ./database/mongo:/data/db:Z
    environment:
      - MONGO_INITDB_ROOT_USERNAME=virtuo
      - MONGO_INITDB_ROOT_PASSWORD=virtuo
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
